### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by andrewbrandwood** [cartridge/cartridge-node-server#4]
# Project version:

0.0.6
## Issue type:
- [ . ] Bug

_**Note**: if you want to suggest a new expansion pack for Cartridge please make sure you are doing so in the [main project repository](https://github.com/cartridge/cartridge/issues/new)._
### Expected behaviour:

404 page should render
### Actual behaviour:

node service errors
### Steps to reproduce the behaviour:

attempt to access a page that doesn't exist

**Comment by mmacartney10** [comment]
This issue has already been fixed
